services:
  - type: web
    name: evolution-api
    runtime: image
    image:
      url: docker.io/atendai/evolution-api:v2.1.1
    plan: free  # Usa 'pro' para 24/7
    region: frankfurt  # Ajusta (ej. oregon)
    envVars:
      - key: SERVER_URL
        value: https://evolution-api-<tuclave123>.onrender.com
      - key: AUTHENTICATION_API_KEY
        sync: false  # Configura manualmente en Render
      - key: DATABASE_ENABLED
        value: true
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_CONNECTION_URI
        fromDatabase:
          name: evolution-db
          property: connectionString
      - key: CACHE_REDIS_ENABLED
        value: true
      - key: CACHE_REDIS_URI
        fromService:
          type: redis
          name: evolution-redis
          property: connectionString
      - key: CACHE_REDIS_PREFIX_KEY
        value: evolution
      - key: TZ
        value: Atlantic/Canary
    numInstances: 1
    port: 8080

databases:
  - name: evolution-db
    databaseName: evolution
    user: evolution_user
    plan: free  # Usa 'pro' para 24/7
    region: frankfurt
    ipAllowList: []  # Solo conexiones internas

services:
  - type: redis
    name: evolution-redis
    plan: free  # Usa 'pro' para 24/7
    region: frankfurt
    ipAllowList: []  # Solo conexiones internas
    maxmemoryPolicy: noeviction
